[package]
name = "sqlx-core"
version = "0.1.1"
repository = "https://github.com/launchbadge/sqlx"
description = "Core of SQLx, the rust SQL toolkit. Not intended to be used directly."
license = "MIT OR Apache-2.0"
edition = "2018"
authors = [
    "Ryan Leckey <leckey.ryan@gmail.com>", # ryan@launchbadge.com
    "Austin Bonander <austin.bonander@gmail.com>", # austin@launchbadge.com
    "Zachery Gyurkovitz <zgyurkovitz@gmail.com>", # zach@launchbadge.com
    "Daniel Akhterov <akhterovd@gmail.com>", # daniel@launchbadge.com
]

[features]
default = []
unstable = []
postgres = []
mysql = []

[dependencies]
async-stream = { version = "0.2.0", default-features = false }
async-std = { version = "1.4.0", default-features = false, features = [ "unstable" ] }
bitflags = { version = "1.2.1", default-features = false }
futures-core = { version = "0.3.1", default-features = false }
futures-util = { version = "0.3.11", default-features = false }
log = { version = "0.4.8", default-features = false }
url = { version = "2.1.0", default-features = false }
byteorder = { version = "1.3.2", default-features = false }
memchr = { version = "2.2.1", default-features = false }
md-5 = { version = "0.8.0", default-features = false }
uuid = { version = "0.8.1", default-features = false, optional = true }
chrono = { version = "0.4.10", default-features = false, features = [ "clock" ], optional = true }

[dev-dependencies]
matches = "0.1.8"
